# Production configuration (PostgreSQL)
# IMPORTANT: Set these environment variables in production:
#   - DATABASE_URL: Your PostgreSQL connection string
#   - FLASK_SECRET_KEY: Strong random secret key for sessions
sqlorm_uri: ${DATABASE_URL}
sqlorm_migrations_folder: "../database/migrations"
dramatiq_broker: sqlite://database/tasks.db
assets_tailwind: main.css
secret_key: ${FLASK_SECRET_KEY}
